# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67bb26f281c05d5a64774cd82d24350a3ab1111e25ec6436a63125c9a28927895cf8cd8aad1efbc5eeaa3c24b952d5375c890b858831429b2777aa180cb5996a

test:
  secret_key_base: f868f096333543959e3862a22e8af7ec3a954833e194feda7ae26f9a6bcac621701f32403ee6d45a637b29594917d557edd04a863563c043ac69f5e303571c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
